name: Prueba_4

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "test1" ]
  pull_request:
    branches: [ "test1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  trabajo:
    runs-on: ubuntu-latest
    steps:
      - name: "Say hello"
        run: echo "Welcome back"
  crear_archivo:
    runs-on: ubuntu-latest
    steps:
      - name: create_file
        run: touch '${GITHUB_WORKSPACE}/'hola.txt' 
              echo "it works" > hola.txt
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola mundo de nuevo"
